@baseURL = http://localhost:3030


//hämta alla beställning
GET {{baseURL}}/orders/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g

###

//hämta en beställning
GET {{baseURL}}/orders/634bd3d82ddb528631faf0c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g

###

//Gör en ny beställning
POST {{baseURL}}/orders/63451deec985621bf525fb61
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g

{
    "serviceType": "SSotning",
    "serviceTime": "2022-12-03"
}

###
//Ta bort en beställning
DELETE {{baseURL}}/orders/634bd753c7fcb92a98edcbba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g

### ändra beställning
PATCH {{baseURL}}/orders/634bd3da2ddb528631faf0c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g

{
    "serviceType": "Gräsklippning",
    "serviceTime": "2222-12-03"
}