@baseURL = http://localhost:3030


//hämta alla tjänster
GET {{baseURL}}/services
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g

###
//skapa en ny tjänst
POST {{baseURL}}/services
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g

{
    "serviceType": "Sotning"
}

###
//Ta bort en tjänst
DELETE {{baseURL}}/services/634bc3987f74d1cf019d42f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g


### ändra tjänst
PATCH {{baseURL}}/services/634bc4fdbc53cc3003b7cc93
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMyYWUwNzkyNWYzODI1NTdlYTAyZTgiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTkwOTUyMiwiZXhwIjoxNjY1OTk1OTIyfQ.kCj7METq6BEoOhIKXRLbIDAPy20gYfIhiLA60tY7H0g

{
    "serviceType": "SSotning"
}